### ISSUE TITLE
add PHP xdebug

### ISSUE THREAD

**Issue by hhebbo** [spryker/saltstack#10]
- [ ] Add PHP xdebug extension without enabling it
- [ ] Provide the command to enable it

**Comment by hacfi** [comment]
@hhebbo 
1. Is already available: https://github.com/spryker/saltstack/blob/master/base/php/extensions.sls#L10-L29 / https://github.com/spryker/pillar/blob/master/dev/app/init.sls#L54
2. Here are the two scripts (I recommend placing them in `/usr/local/bin/`):

`enable-xdebug`

```
!/bin/sh

sudo sed -i.bck "s/^;zend_extension=/zend_extension=/" /etc/php5/mods-available/xdebug.ini

sudo /etc/init.d/php5-fpm restart

echo "xdebug enabled"
```

`disable-xdebug`

```
!/bin/sh

sudo sed -i.bck "s/^zend_extension=/;zend_extension=/" /etc/php5/mods-available/xdebug.ini

sudo /etc/init.d/php5-fpm restart

echo "xdebug disabled"
```

Of course you can make this more advanced checking if you actually changed it or not
